//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;

namespace Inedo.BuildMasterExtensions.Axosoft.Data
{
	public static partial class TableNames
	{
		public const string AlertItems = "AlertItems";
		public const string Alerts = "Alerts";
		public const string ApplicationInfo = "ApplicationInfo";
		public const string Attachments = "Attachments";
		public const string AuditTrails = "AuditTrails";
		public const string CategoryTypes = "CategoryTypes";
		public const string Comments = "Comments";
		public const string CustomerContactCustomFields = "CustomerContactCustomFields";
		public const string CustomerContacts = "CustomerContacts";
		public const string CustomerCustomFields = "CustomerCustomFields";
		public const string CustomerPortalSettings = "CustomerPortalSettings";
		public const string Customers = "Customers";
		public const string CustomersProjects = "CustomersProjects";
		public const string DefectCustomFields = "DefectCustomFields";
		public const string Defects = "Defects";
		public const string EmailAttachments = "EmailAttachments";
		public const string EmailMessages = "EmailMessages";
		public const string EmailQueue = "EmailQueue";
		public const string EmailTemplates = "EmailTemplates";
		public const string EscalationLevels = "EscalationLevels";
		public const string Escalations = "Escalations";
		public const string Exceptions = "Exceptions";
		public const string FeatureCustomFields = "FeatureCustomFields";
		public const string Features = "Features";
		public const string FieldChangeAlertQueue = "FieldChangeAlertQueue";
		public const string Fields = "Fields";
		public const string FieldTemplateDetails = "FieldTemplateDetails";
		public const string FieldTemplateGroups = "FieldTemplateGroups";
		public const string FieldTemplates = "FieldTemplates";
		public const string FilterableColumns = "FilterableColumns";
		public const string FilterConditions = "FilterConditions";
		public const string FilterOperators = "FilterOperators";
		public const string Filters = "Filters";
		public const string GlobalSettings = "GlobalSettings";
		public const string ImportTemplates = "ImportTemplates";
		public const string IncidentCustomFields = "IncidentCustomFields";
		public const string Incidents = "Incidents";
		public const string ItemRelations = "ItemRelations";
		public const string ItemRelationTypes = "ItemRelationTypes";
		public const string LockManager = "LockManager";
		public const string MailAccounts = "MailAccounts";
		public const string MimeTypes = "MimeTypes";
		public const string NotificationListDetails = "NotificationListDetails";
		public const string NotificationLists = "NotificationLists";
		public const string NotificationSettings = "NotificationSettings";
		public const string PickLists = "PickLists";
		public const string PickListValues = "PickListValues";
		public const string PriorityTypes = "PriorityTypes";
		public const string ProjectCustomFields = "ProjectCustomFields";
		public const string ProjectEscalationSettings = "ProjectEscalationSettings";
		public const string ProjectFieldTemplateSettings = "ProjectFieldTemplateSettings";
		public const string Projects = "Projects";
		public const string ProjectWorkflowSettings = "ProjectWorkflowSettings";
		public const string ReleaseProjects = "ReleaseProjects";
		public const string Releases = "Releases";
		public const string ReleaseStatusTypes = "ReleaseStatusTypes";
		public const string ReleaseTypes = "ReleaseTypes";
		public const string ReleaseWorkEntries = "ReleaseWorkEntries";
		public const string Reports = "Reports";
		public const string ReportShortcuts = "ReportShortcuts";
		public const string ResponseTemplates = "ResponseTemplates";
		public const string Schedules = "Schedules";
		public const string SCMLinks = "SCMLinks";
		public const string SCMSettings = "SCMSettings";
		public const string SecurityCategories = "SecurityCategories";
		public const string SecurityFeatures = "SecurityFeatures";
		public const string SecurityRoleFeatures = "SecurityRoleFeatures";
		public const string SecurityRoleFields = "SecurityRoleFields";
		public const string SecurityRoleProjects = "SecurityRoleProjects";
		public const string SecurityRoleReports = "SecurityRoleReports";
		public const string SecurityRoles = "SecurityRoles";
		public const string SeverityTypes = "SeverityTypes";
		public const string StatusTypes = "StatusTypes";
		public const string TaskCustomFields = "TaskCustomFields";
		public const string Tasks = "Tasks";
		public const string TempAppData = "TempAppData";
		public const string TimeUnitTypes = "TimeUnitTypes";
		public const string UserLogins = "UserLogins";
		public const string Users = "Users";
		public const string UserSecurityRoles = "UserSecurityRoles";
		public const string Views = "Views";
		public const string Votes = "Votes";
		public const string VotesView = "VotesView";
		public const string WikiPageHistory = "WikiPageHistory";
		public const string WikiPages = "WikiPages";
		public const string Workflows = "Workflows";
		public const string WorkflowStepRelations = "WorkflowStepRelations";
		public const string WorkflowStepRelationSecurity = "WorkflowStepRelationSecurity";
		public const string WorkflowSteps = "WorkflowSteps";
		public const string WorkLog = "WorkLog";
		public const string WorkLogCustomFields = "WorkLogCustomFields";
		public const string WorkLogTypes = "WorkLogTypes";
	}
}
