//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;

namespace Inedo.BuildMasterExtensions.Axosoft.Data
{
	public static partial class TableDefs
	{
		public class AlertItems
		{
			public const string AlertId = "AlertId";
			public const string ItemId = "ItemId";
			public const string Email = "Email";
		}

		public class Alerts
		{
			public const string AlertId = "AlertId";
			public const string AlertItemType = "AlertItemType";
			public const string ItemType = "ItemType";
			public const string AlertItemId = "AlertItemId";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string UserId = "UserId";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string TriggerType = "TriggerType";
			public const string TriggerDetailsXML = "TriggerDetailsXML";
			public const string NotificationListId = "NotificationListId";
			public const string RunProcess = "RunProcess";
			public const string ProcessPath = "ProcessPath";
			public const string ProcessArguments = "ProcessArguments";
			public const string LastRefreshDateTime = "LastRefreshDateTime";
			public const string IsActive = "IsActive";
			public const string LockDateTime = "LockDateTime";
		}

		public class ApplicationInfo
		{
			public const string DatabaseVersion = "DatabaseVersion";
			public const string MinProductVersionsXml = "MinProductVersionsXml";
			public const string ActivationGuid = "ActivationGuid";
			public const string ActivationXml = "ActivationXml";
			public const string LastUpgradedDatabaseVersion = "LastUpgradedDatabaseVersion";
			public const string LastUpgradedDateTime = "LastUpgradedDateTime";
		}

		public class Attachments
		{
			public const string AttachmentId = "AttachmentId";
			public const string SourceType = "SourceType";
			public const string SourceId = "SourceId";
			public const string CreatedById = "CreatedById";
			public const string FileName = "FileName";
			public const string AttachDate = "AttachDate";
			public const string Description = "Description";
			public const string StoreInDB = "StoreInDB";
			public const string FullPath = "FullPath";
			public const string FileData = "FileData";
			public const string IsEmbedded = "IsEmbedded";
			public const string DataHash = "DataHash";
		}

		public class AuditTrails
		{
			public const string AuditTrailId = "AuditTrailId";
			public const string AuditType = "AuditType";
			public const string ItemType = "ItemType";
			public const string ItemId = "ItemId";
			public const string ItemNumber = "ItemNumber";
			public const string ItemName = "ItemName";
			public const string ItemProjectId = "ItemProjectId";
			public const string ItemReleaseId = "ItemReleaseId";
			public const string AuditDateTime = "AuditDateTime";
			public const string AuditSource = "AuditSource";
			public const string UserId = "UserId";
			public const string UserType = "UserType";
			public const string ChangesXml = "ChangesXml";
			public const string Archived = "Archived";
		}

		public class CategoryTypes
		{
			public const string CategoryTypeId = "CategoryTypeId";
			public const string Name = "Name";
			public const string DisplayOrder = "DisplayOrder";
			public const string OwnerId = "OwnerId";
		}

		public class Comments
		{
			public const string CommentId = "CommentId";
			public const string CommentType = "CommentType";
			public const string CommentText = "CommentText";
			public const string CreatedById = "CreatedById";
			public const string CreatedByType = "CreatedByType";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string ItemType = "ItemType";
			public const string ItemId = "ItemId";
			public const string FieldId = "FieldId";
		}

		public class CustomerContactCustomFields
		{
			public const string CustomerContactId = "CustomerContactId";
			public const string Custom_126 = "Custom_126";
			public const string Custom_128 = "Custom_128";
			public const string Custom_129 = "Custom_129";
			public const string Custom_130 = "Custom_130";
			public const string Custom_131 = "Custom_131";
		}

		public class CustomerContacts
		{
			public const string CustomerContactId = "CustomerContactId";
			public const string CustomerId = "CustomerId";
			public const string FirstName = "FirstName";
			public const string LastName = "LastName";
			public const string Email = "Email";
			public const string Phone = "Phone";
			public const string Password = "Password";
			public const string Status = "Status";
			public const string AllowDefectViewOwn = "AllowDefectViewOwn";
			public const string AllowDefectViewPublic = "AllowDefectViewPublic";
			public const string AllowDefectAdd = "AllowDefectAdd";
			public const string AllowDefectEditOwn = "AllowDefectEditOwn";
			public const string AllowDefectEditPublic = "AllowDefectEditPublic";
			public const string AllowDefectViewAttachmentOwn = "AllowDefectViewAttachmentOwn";
			public const string AllowDefectViewAttachmentPublic = "AllowDefectViewAttachmentPublic";
			public const string AllowDefectAddAttachmentOwn = "AllowDefectAddAttachmentOwn";
			public const string AllowDefectAddAttachmentPublic = "AllowDefectAddAttachmentPublic";
			public const string IncludeCompanyDefects = "IncludeCompanyDefects";
			public const string AllowFeatureViewOwn = "AllowFeatureViewOwn";
			public const string AllowFeatureViewPublic = "AllowFeatureViewPublic";
			public const string AllowFeatureAdd = "AllowFeatureAdd";
			public const string AllowFeatureEditOwn = "AllowFeatureEditOwn";
			public const string AllowFeatureEditPublic = "AllowFeatureEditPublic";
			public const string AllowFeatureViewAttachmentOwn = "AllowFeatureViewAttachmentOwn";
			public const string AllowFeatureViewAttachmentPublic = "AllowFeatureViewAttachmentPublic";
			public const string AllowFeatureAddAttachmentOwn = "AllowFeatureAddAttachmentOwn";
			public const string AllowFeatureAddAttachmentPublic = "AllowFeatureAddAttachmentPublic";
			public const string IncludeCompanyFeatures = "IncludeCompanyFeatures";
			public const string AllowTaskViewOwn = "AllowTaskViewOwn";
			public const string AllowTaskViewPublic = "AllowTaskViewPublic";
			public const string AllowTaskAdd = "AllowTaskAdd";
			public const string AllowTaskEditOwn = "AllowTaskEditOwn";
			public const string AllowTaskEditPublic = "AllowTaskEditPublic";
			public const string AllowTaskViewAttachmentOwn = "AllowTaskViewAttachmentOwn";
			public const string AllowTaskViewAttachmentPublic = "AllowTaskViewAttachmentPublic";
			public const string AllowTaskAddAttachmentOwn = "AllowTaskAddAttachmentOwn";
			public const string AllowTaskAddAttachmentPublic = "AllowTaskAddAttachmentPublic";
			public const string IncludeCompanyTasks = "IncludeCompanyTasks";
			public const string AllowIncidentViewOwn = "AllowIncidentViewOwn";
			public const string AllowIncidentViewPublic = "AllowIncidentViewPublic";
			public const string AllowIncidentAdd = "AllowIncidentAdd";
			public const string AllowIncidentEditOwn = "AllowIncidentEditOwn";
			public const string AllowIncidentEditPublic = "AllowIncidentEditPublic";
			public const string AllowIncidentViewAttachmentOwn = "AllowIncidentViewAttachmentOwn";
			public const string AllowIncidentViewAttachmentPublic = "AllowIncidentViewAttachmentPublic";
			public const string AllowIncidentAddAttachmentOwn = "AllowIncidentAddAttachmentOwn";
			public const string AllowIncidentAddAttachmentPublic = "AllowIncidentAddAttachmentPublic";
			public const string IncludeCompanyIncidents = "IncludeCompanyIncidents";
			public const string SettingsXML = "SettingsXML";
			public const string CanLogin = "CanLogin";
			public const string AllowViewPublicWikiPages = "AllowViewPublicWikiPages";
			public const string AllowEditPublicWikiPages = "AllowEditPublicWikiPages";
			public const string AllowAddPublicWikiPages = "AllowAddPublicWikiPages";
			public const string AllowAddWikiAttachments = "AllowAddWikiAttachments";
			public const string AllowViewWikiComments = "AllowViewWikiComments";
			public const string AllowAddWikiComments = "AllowAddWikiComments";
		}

		public class CustomerCustomFields
		{
			public const string CustomerId = "CustomerId";
			public const string Custom_124 = "Custom_124";
			public const string Custom_125 = "Custom_125";
		}

		public class CustomerPortalSettings
		{
			public const string CustomerPortalSettingsXml = "CustomerPortalSettingsXml";
		}

		public class Customers
		{
			public const string CustomerId = "CustomerId";
			public const string CompanyName = "CompanyName";
			public const string CompanyURL = "CompanyURL";
			public const string DefectViewProjectId = "DefectViewProjectId";
			public const string DefectViewFilterId = "DefectViewFilterId";
			public const string DefectAddEditProjectId = "DefectAddEditProjectId";
			public const string FeatureViewProjectId = "FeatureViewProjectId";
			public const string FeatureViewFilterId = "FeatureViewFilterId";
			public const string FeatureAddEditProjectId = "FeatureAddEditProjectId";
			public const string TaskViewProjectId = "TaskViewProjectId";
			public const string TaskViewFilterId = "TaskViewFilterId";
			public const string TaskAddEditProjectId = "TaskAddEditProjectId";
			public const string IncidentViewProjectId = "IncidentViewProjectId";
			public const string IncidentViewFilterId = "IncidentViewFilterId";
			public const string IncidentAddEditProjectId = "IncidentAddEditProjectId";
			public const string WikiPageViewProjectId = "WikiPageViewProjectId";
			public const string WikiPageAddEditProjectId = "WikiPageAddEditProjectId";
		}

		public class CustomersProjects
		{
			public const string CustomerId = "CustomerId";
			public const string ProjectId = "ProjectId";
		}

		public class DefectCustomFields
		{
			public const string DefectId = "DefectId";
			public const string Custom_139 = "Custom_139";
			public const string Custom_141 = "Custom_141";
			public const string Custom_142 = "Custom_142";
		}

		public class Defects
		{
			public const string DefectId = "DefectId";
			public const string ProjectId = "ProjectId";
			public const string CreatorId = "CreatorId";
			public const string ReportedById = "ReportedById";
			public const string AssignedToId = "AssignedToId";
			public const string PriorityTypeId = "PriorityTypeId";
			public const string StatusTypeId = "StatusTypeId";
			public const string SeverityTypeId = "SeverityTypeId";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string BuildNumber = "BuildNumber";
			public const string EstimatedDuration = "EstimatedDuration";
			public const string DurationUnitTypeId = "DurationUnitTypeId";
			public const string ActualDuration = "ActualDuration";
			public const string ActualUnitTypeId = "ActualUnitTypeId";
			public const string DateFound = "DateFound";
			public const string DateFixed = "DateFixed";
			public const string DueDate = "DueDate";
			public const string BuildNumberOfFix = "BuildNumberOfFix";
			public const string ReplicationProcedures = "ReplicationProcedures";
			public const string Resolution = "Resolution";
			public const string Notes = "Notes";
			public const string LastUpdated = "LastUpdated";
			public const string WorkflowStepId = "WorkflowStepId";
			public const string PercentComplete = "PercentComplete";
			public const string LastUpdatedById = "LastUpdatedById";
			public const string LastUpdatedDateTime = "LastUpdatedDateTime";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string PubliclyViewable = "PubliclyViewable";
			public const string ReportedByCustomerContactId = "ReportedByCustomerContactId";
			public const string Archived = "Archived";
			public const string RemainingDuration = "RemainingDuration";
			public const string RemainingUnitTypeId = "RemainingUnitTypeId";
			public const string ReleaseId = "ReleaseId";
		}

		public class EmailAttachments
		{
			public const string EmailAttachmentId = "EmailAttachmentId";
			public const string AttachmentId = "AttachmentId";
			public const string EmailMessageId = "EmailMessageId";
		}

		public class EmailMessages
		{
			public const string EmailMessageId = "EmailMessageId";
			public const string MailAccountId = "MailAccountId";
			public const string EmailMessageSender = "EmailMessageSender";
			public const string EmailMessageTo = "EmailMessageTo";
			public const string EmailMessageCC = "EmailMessageCC";
			public const string EmailMessageBCC = "EmailMessageBCC";
			public const string EmailMessageSubject = "EmailMessageSubject";
			public const string EmailBody = "EmailBody";
			public const string SentDate = "SentDate";
			public const string ItemId = "ItemId";
			public const string ItemType = "ItemType";
			public const string IsIncomingMessage = "IsIncomingMessage";
			public const string IsAutoReply = "IsAutoReply";
		}

		public class EmailQueue
		{
			public const string EmailId = "EmailId";
			public const string EmailDetailsXML = "EmailDetailsXML";
			public const string NumAttempts = "NumAttempts";
			public const string CreatedDate = "CreatedDate";
			public const string LastSentDate = "LastSentDate";
			public const string LockDateTime = "LockDateTime";
		}

		public class EmailTemplates
		{
			public const string EmailTemplateId = "EmailTemplateId";
			public const string EmailTemplateType = "EmailTemplateType";
			public const string UserType = "UserType";
			public const string ItemType = "ItemType";
			public const string EmailTemplateDetailType = "EmailTemplateDetailType";
			public const string MessageType = "MessageType";
			public const string EmailFrom = "EmailFrom";
			public const string EmailSubject = "EmailSubject";
			public const string EmailBody = "EmailBody";
			public const string EmailFieldsXml = "EmailFieldsXml";
		}

		public class EscalationLevels
		{
			public const string EscalationLevelId = "EscalationLevelId";
			public const string EscalationId = "EscalationId";
			public const string Name = "Name";
			public const string LevelNumber = "LevelNumber";
		}

		public class Escalations
		{
			public const string EscalationId = "EscalationId";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string AllowSkipping = "AllowSkipping";
		}

		public class Exceptions
		{
			public const string ExceptionId = "ExceptionId";
			public const string Source = "Source";
			public const string TargetSite = "TargetSite";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string InnerException = "InnerException";
			public const string UserId = "UserId";
			public const string Message = "Message";
			public const string StackTrace = "StackTrace";
			public const string AdditionalInfo = "AdditionalInfo";
			public const string ExceptionType = "ExceptionType";
		}

		public class FeatureCustomFields
		{
			public const string FeatureId = "FeatureId";
			public const string Custom_143 = "Custom_143";
			public const string Custom_144 = "Custom_144";
			public const string Custom_145 = "Custom_145";
			public const string Custom_146 = "Custom_146";
			public const string Custom_150 = "Custom_150";
		}

		public class Features
		{
			public const string FeatureId = "FeatureId";
			public const string ProjectId = "ProjectId";
			public const string CreatorId = "CreatorId";
			public const string PlannedBuildNumber = "PlannedBuildNumber";
			public const string AssignedToId = "AssignedToId";
			public const string RequestedById = "RequestedById";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string EstimatedDuration = "EstimatedDuration";
			public const string DurationUnitTypeId = "DurationUnitTypeId";
			public const string ActualDuration = "ActualDuration";
			public const string ActualUnitTypeId = "ActualUnitTypeId";
			public const string CompletionDate = "CompletionDate";
			public const string PriorityTypeId = "PriorityTypeId";
			public const string StatusTypeId = "StatusTypeId";
			public const string PercentComplete = "PercentComplete";
			public const string StartDate = "StartDate";
			public const string DueDate = "DueDate";
			public const string Notes = "Notes";
			public const string LastUpdated = "LastUpdated";
			public const string WorkflowStepId = "WorkflowStepId";
			public const string LastUpdatedById = "LastUpdatedById";
			public const string LastUpdatedDateTime = "LastUpdatedDateTime";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string PubliclyViewable = "PubliclyViewable";
			public const string RequestedByCustomerContactId = "RequestedByCustomerContactId";
			public const string Archived = "Archived";
			public const string RemainingDuration = "RemainingDuration";
			public const string RemainingUnitTypeId = "RemainingUnitTypeId";
			public const string ReleaseId = "ReleaseId";
		}

		public class FieldChangeAlertQueue
		{
			public const string FieldChangeAlertQueueId = "FieldChangeAlertQueueId";
			public const string AlertId = "AlertId";
			public const string ItemId = "ItemId";
			public const string ItemType = "ItemType";
			public const string AlertDateTime = "AlertDateTime";
			public const string AlertDetailsXML = "AlertDetailsXML";
			public const string LockDateTime = "LockDateTime";
		}

		public class Fields
		{
			public const string FieldId = "FieldId";
			public const string TableFieldName = "TableFieldName";
			public const string FieldType = "FieldType";
			public const string RecordType = "RecordType";
			public const string FieldLabel = "FieldLabel";
			public const string PickListId = "PickListId";
			public const string StringSize = "StringSize";
			public const string Format = "Format";
			public const string DisplayOrder = "DisplayOrder";
			public const string IsEditable = "IsEditable";
			public const string IsCustomField = "IsCustomField";
			public const string IsMultiSelect = "IsMultiSelect";
			public const string IsGroupable = "IsGroupable";
			public const string IsSearchable = "IsSearchable";
			public const string SortExpression = "SortExpression";
			public const string SelectExpression = "SelectExpression";
		}

		public class FieldTemplateDetails
		{
			public const string FieldTemplateDetailId = "FieldTemplateDetailId";
			public const string FieldTemplateId = "FieldTemplateId";
			public const string FieldTemplateGroupId = "FieldTemplateGroupId";
			public const string FieldId = "FieldId";
			public const string DefaultValue = "DefaultValue";
			public const string DisplayOrder = "DisplayOrder";
			public const string Required = "Required";
			public const string Selected = "Selected";
			public const string Editable = "Editable";
		}

		public class FieldTemplateGroups
		{
			public const string FieldTemplateGroupId = "FieldTemplateGroupId";
			public const string FieldTemplateId = "FieldTemplateId";
			public const string Label = "Label";
			public const string DisplayOrder = "DisplayOrder";
		}

		public class FieldTemplates
		{
			public const string FieldTemplateId = "FieldTemplateId";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string ItemType = "ItemType";
			public const string IsActive = "IsActive";
		}

		public class FilterableColumns
		{
			public const string FilterableColumnId = "FilterableColumnId";
			public const string FilterType = "FilterType";
			public const string ResourceName = "ResourceName";
			public const string DatabaseField = "DatabaseField";
			public const string ColumnType = "ColumnType";
			public const string ListValueColumn = "ListValueColumn";
			public const string ListDisplayColumn = "ListDisplayColumn";
			public const string ListParentColumn = "ListParentColumn";
			public const string ListSelectSproc = "ListSelectSproc";
			public const string UseResourceName = "UseResourceName";
		}

		public class FilterConditions
		{
			public const string FilterConditionId = "FilterConditionId";
			public const string FilterId = "FilterId";
			public const string FilterableColumnId = "FilterableColumnId";
			public const string FilterOperatorId = "FilterOperatorId";
			public const string FilterValue1 = "FilterValue1";
			public const string FilterValue2 = "FilterValue2";
			public const string OpenParenthesis = "OpenParenthesis";
			public const string CloseParenthesis = "CloseParenthesis";
			public const string ConditionOrder = "ConditionOrder";
			public const string IsAnd = "IsAnd";
		}

		public class FilterOperators
		{
			public const string FilterOperatorId = "FilterOperatorId";
			public const string ColumnType = "ColumnType";
			public const string Operator = "Operator";
			public const string ResourceName = "ResourceName";
		}

		public class Filters
		{
			public const string FilterId = "FilterId";
			public const string Name = "Name";
			public const string UserId = "UserId";
			public const string Private = "Private";
			public const string FilterType = "FilterType";
		}

		public class GlobalSettings
		{
			public const string GlobalSettingsXml = "GlobalSettingsXml";
			public const string IncidentNumberPrefix = "IncidentNumberPrefix";
			public const string IncidentNextNumber = "IncidentNextNumber";
			public const string IncidentNumberFixedWidth = "IncidentNumberFixedWidth";
			public const string LastUpdated = "LastUpdated";
			public const string StoredProceduresVersion = "StoredProceduresVersion";
			public const string IsHosted = "IsHosted";
		}

		public class ImportTemplates
		{
			public const string ImportTemplateId = "ImportTemplateId";
			public const string Name = "Name";
			public const string TemplateXml = "TemplateXml";
			public const string TemplateType = "TemplateType";
		}

		public class IncidentCustomFields
		{
			public const string IncidentId = "IncidentId";
			public const string Custom_147 = "Custom_147";
			public const string Custom_148 = "Custom_148";
			public const string Custom_151 = "Custom_151";
		}

		public class Incidents
		{
			public const string IncidentId = "IncidentId";
			public const string IncidentNumber = "IncidentNumber";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string ReplicationProcedures = "ReplicationProcedures";
			public const string Resolution = "Resolution";
			public const string Notes = "Notes";
			public const string PriorityTypeId = "PriorityTypeId";
			public const string StatusTypeId = "StatusTypeId";
			public const string SeverityTypeId = "SeverityTypeId";
			public const string ProjectId = "ProjectId";
			public const string ReportedById = "ReportedById";
			public const string AssignedToId = "AssignedToId";
			public const string WorkflowStepId = "WorkflowStepId";
			public const string ReportedByCustomerContactId = "ReportedByCustomerContactId";
			public const string PubliclyViewable = "PubliclyViewable";
			public const string ReportedDate = "ReportedDate";
			public const string StartDate = "StartDate";
			public const string DueDate = "DueDate";
			public const string CompletionDate = "CompletionDate";
			public const string ActualDuration = "ActualDuration";
			public const string ActualUnitTypeId = "ActualUnitTypeId";
			public const string EstimatedDuration = "EstimatedDuration";
			public const string DurationUnitTypeId = "DurationUnitTypeId";
			public const string PercentComplete = "PercentComplete";
			public const string EscalationLevelId = "EscalationLevelId";
			public const string Archived = "Archived";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string CreatedById = "CreatedById";
			public const string LastUpdatedDateTime = "LastUpdatedDateTime";
			public const string LastUpdatedById = "LastUpdatedById";
			public const string LastUpdated = "LastUpdated";
			public const string RemainingDuration = "RemainingDuration";
			public const string RemainingUnitTypeId = "RemainingUnitTypeId";
			public const string ReleaseId = "ReleaseId";
		}

		public class ItemRelations
		{
			public const string ItemRelationId = "ItemRelationId";
			public const string ParentItemId = "ParentItemId";
			public const string ParentItemTypeId = "ParentItemTypeId";
			public const string ChildItemId = "ChildItemId";
			public const string ChildItemTypeId = "ChildItemTypeId";
			public const string ItemRelationTypeId = "ItemRelationTypeId";
			public const string ItemRelationCreateDateTime = "ItemRelationCreateDateTime";
			public const string ItemRelationUserId = "ItemRelationUserId";
			public const string ItemRelationDescription = "ItemRelationDescription";
		}

		public class ItemRelationTypes
		{
			public const string ItemRelationTypeId = "ItemRelationTypeId";
			public const string DisplayOrder = "DisplayOrder";
			public const string Name = "Name";
			public const string ParentDescription = "ParentDescription";
			public const string ChildDescription = "ChildDescription";
		}

		public class LockManager
		{
			public const string LockId = "LockId";
			public const string ItemId = "ItemId";
			public const string LockType = "LockType";
			public const string UserId = "UserId";
			public const string UserType = "UserType";
			public const string LockCreatedDateTime = "LockCreatedDateTime";
			public const string LockDateTime = "LockDateTime";
			public const string SessionId = "SessionId";
		}

		public class MailAccounts
		{
			public const string AccountId = "AccountId";
			public const string AccountProtocol = "AccountProtocol";
			public const string Server = "Server";
			public const string UserName = "UserName";
			public const string Password = "Password";
			public const string RequireSsl = "RequireSsl";
			public const string EmailAddress = "EmailAddress";
			public const string Port = "Port";
			public const string TimerInterval = "TimerInterval";
			public const string ItemType = "ItemType";
			public const string FieldTemplateXML = "FieldTemplateXML";
			public const string SubjectFieldId = "SubjectFieldId";
			public const string BodyFieldId = "BodyFieldId";
			public const string SenderFieldId = "SenderFieldId";
			public const string SaveAttachments = "SaveAttachments";
			public const string IsActive = "IsActive";
			public const string SendResponse = "SendResponse";
			public const string SendResponseAll = "SendResponseAll";
			public const string ResponseFrom = "ResponseFrom";
			public const string ResponseSubject = "ResponseSubject";
			public const string ResponseBody = "ResponseBody";
			public const string LastCheckedDateTime = "LastCheckedDateTime";
			public const string ServiceUserId = "ServiceUserId";
			public const string NotifySender = "NotifySender";
			public const string UseBlacklistChecker = "UseBlacklistChecker";
			public const string SendConversationResponse = "SendConversationResponse";
			public const string AttemptAutoAssign = "AttemptAutoAssign";
			public const string LockDateTime = "LockDateTime";
			public const string DeleteMessages = "DeleteMessages";
			public const string ViewedMessages = "ViewedMessages";
			public const string IgnorePhrases = "IgnorePhrases";
			public const string IgnoredMessages = "IgnoredMessages";
			public const string MailFormat = "MailFormat";
			public const string SendAllNotificationsOnAdd = "SendAllNotificationsOnAdd";
			public const string NewEmailAction = "NewEmailAction";
			public const string NewEmailStatusId = "NewEmailStatusId";
			public const string ViewedMessageHashes = "ViewedMessageHashes";
			public const string IgnoredMessageHashes = "IgnoredMessageHashes";
			public const string AccountDetails = "AccountDetails";
		}

		public class MimeTypes
		{
			public const string MimeTypeId = "MimeTypeId";
			public const string ContentType = "ContentType";
			public const string FileExtension = "FileExtension";
		}

		public class NotificationListDetails
		{
			public const string NotificationListDetailId = "NotificationListDetailId";
			public const string NotificationListId = "NotificationListId";
			public const string UserId = "UserId";
			public const string UserTypeId = "UserTypeId";
			public const string EmailAddress = "EmailAddress";
		}

		public class NotificationLists
		{
			public const string NotificationListId = "NotificationListId";
			public const string ItemId = "ItemId";
			public const string NotificationTypeId = "NotificationTypeId";
			public const string ItemTypeId = "ItemTypeId";
			public const string ItemChangeTypeId = "ItemChangeTypeId";
			public const string NotificationDetailType = "NotificationDetailType";
		}

		public class NotificationSettings
		{
			public const string NotificationSettingsId = "NotificationSettingsId";
			public const string DoNotNotifyCauser = "DoNotNotifyCauser";
			public const string SmtpServer = "SmtpServer";
			public const string SmtpPort = "SmtpPort";
			public const string SmtpUseSsl = "SmtpUseSsl";
			public const string SmtpRequiresAuth = "SmtpRequiresAuth";
			public const string SmtpUserId = "SmtpUserId";
			public const string SmtpPassword = "SmtpPassword";
			public const string SmtpAssembly = "SmtpAssembly";
			public const string WebLinkBaseURL = "WebLinkBaseURL";
			public const string IncludeHistory = "IncludeHistory";
			public const string SendNotifications = "SendNotifications";
			public const string SendNotificationsToInactiveUsers = "SendNotificationsToInactiveUsers";
			public const string UseEmailQueue = "UseEmailQueue";
			public const string EmailQueueMaxSendAttempts = "EmailQueueMaxSendAttempts";
			public const string MaxAttachmentSize = "MaxAttachmentSize";
			public const string DefaultMessageEncoding = "DefaultMessageEncoding";
			public const string LastUpdated = "LastUpdated";
		}

		public class PickLists
		{
			public const string PickListId = "PickListId";
			public const string Name = "Name";
			public const string ParentPickListId = "ParentPickListId";
			public const string Path = "Path";
			public const string PickListType = "PickListType";
			public const string PickListSelectSproc = "PickListSelectSproc";
			public const string PickListDisplayColumn = "PickListDisplayColumn";
		}

		public class PickListValues
		{
			public const string PickListValueId = "PickListValueId";
			public const string PickListId = "PickListId";
			public const string Value = "Value";
			public const string DisplayOrder = "DisplayOrder";
			public const string ParentPickListValueId = "ParentPickListValueId";
		}

		public class PriorityTypes
		{
			public const string PriorityTypeId = "PriorityTypeId";
			public const string Name = "Name";
			public const string DisplayOrder = "DisplayOrder";
			public const string DefaultColor = "DefaultColor";
		}

		public class ProjectCustomFields
		{
			public const string ProjectId = "ProjectId";
			public const string Custom_132 = "Custom_132";
			public const string Custom_133 = "Custom_133";
			public const string Custom_134 = "Custom_134";
			public const string Custom_135 = "Custom_135";
			public const string Custom_136 = "Custom_136";
			public const string Custom_137 = "Custom_137";
			public const string Custom_138 = "Custom_138";
		}

		public class ProjectEscalationSettings
		{
			public const string ProjectEscalationSettingId = "ProjectEscalationSettingId";
			public const string ProjectId = "ProjectId";
			public const string ItemType = "ItemType";
			public const string EscalationId = "EscalationId";
			public const string InheritsEscalation = "InheritsEscalation";
		}

		public class ProjectFieldTemplateSettings
		{
			public const string ProjectFieldTemplateSettingId = "ProjectFieldTemplateSettingId";
			public const string ProjectId = "ProjectId";
			public const string ItemType = "ItemType";
			public const string ViewFieldTemplateId = "ViewFieldTemplateId";
			public const string AddFieldTemplateId = "AddFieldTemplateId";
			public const string EditFieldTemplateId = "EditFieldTemplateId";
			public const string InheritsFieldTemplate = "InheritsFieldTemplate";
			public const string Product = "Product";
		}

		public class Projects
		{
			public const string ProjectId = "ProjectId";
			public const string ParentId = "ParentId";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string StartDate = "StartDate";
			public const string DueDate = "DueDate";
			public const string IsActive = "IsActive";
			public const string Path = "Path";
		}

		public class ProjectWorkflowSettings
		{
			public const string ProjectWorkflowSettingId = "ProjectWorkflowSettingId";
			public const string ProjectId = "ProjectId";
			public const string ItemType = "ItemType";
			public const string WorkflowId = "WorkflowId";
			public const string InheritsWorkflow = "InheritsWorkflow";
			public const string NewItemWorkflowStepId = "NewItemWorkflowStepId";
			public const string MovedItemWorkflowStepId = "MovedItemWorkflowStepId";
			public const string EnforceWorkflow = "EnforceWorkflow";
			public const string EnforceNewItemStep = "EnforceNewItemStep";
			public const string KeepMovedItemStep = "KeepMovedItemStep";
		}

		public class ReleaseProjects
		{
			public const string ReleaseId = "ReleaseId";
			public const string ProjectId = "ProjectId";
		}

		public class Releases
		{
			public const string ReleaseId = "ReleaseId";
			public const string ParentReleaseId = "ParentReleaseId";
			public const string ReleaseTypeId = "ReleaseTypeId";
			public const string Name = "Name";
			public const string StartDate = "StartDate";
			public const string DueDate = "DueDate";
			public const string ReleaseStatusTypeId = "ReleaseStatusTypeId";
			public const string Path = "Path";
			public const string IsActive = "IsActive";
			public const string VelocityStartDate = "VelocityStartDate";
			public const string ReleaseNotes = "ReleaseNotes";
		}

		public class ReleaseStatusTypes
		{
			public const string ReleaseStatusTypeId = "ReleaseStatusTypeId";
			public const string ReleaseTypeId = "ReleaseTypeId";
			public const string Name = "Name";
			public const string DisplayOrder = "DisplayOrder";
		}

		public class ReleaseTypes
		{
			public const string ReleaseTypeId = "ReleaseTypeId";
			public const string Name = "Name";
			public const string Level = "Level";
			public const string Icon = "Icon";
		}

		public class ReleaseWorkEntries
		{
			public const string ReleaseWorkEntryId = "ReleaseWorkEntryId";
			public const string ReleaseId = "ReleaseId";
			public const string EntryDateTime = "EntryDateTime";
			public const string WorkMinutes = "WorkMinutes";
			public const string ItemId = "ItemId";
			public const string ItemType = "ItemType";
		}

		public class Reports
		{
			public const string ReportId = "ReportId";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string ReportClass = "ReportClass";
			public const string ReportXml = "ReportXml";
			public const string SqlCommand = "SqlCommand";
			public const string ReportType = "ReportType";
			public const string IsActive = "IsActive";
			public const string CreatedById = "CreatedById";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string LastUpdatedById = "LastUpdatedById";
			public const string LastUpdatedDateTime = "LastUpdatedDateTime";
		}

		public class ReportShortcuts
		{
			public const string ReportShortcutId = "ReportShortcutId";
			public const string ReportId = "ReportId";
			public const string Name = "Name";
			public const string FilterId = "FilterId";
			public const string FilterSql = "FilterSql";
			public const string FilterAuto = "FilterAuto";
			public const string SortSql = "SortSql";
			public const string UserId = "UserId";
			public const string IsPublic = "IsPublic";
		}

		public class ResponseTemplates
		{
			public const string ResponseTemplateId = "ResponseTemplateId";
			public const string Name = "Name";
			public const string Response = "Response";
			public const string Shortcut = "Shortcut";
			public const string UserId = "UserId";
			public const string Private = "Private";
			public const string ItemType = "ItemType";
		}

		public class Schedules
		{
			public const string ScheduleId = "ScheduleId";
			public const string StartDate = "StartDate";
			public const string ScheduleItemId = "ScheduleItemId";
			public const string ScheduleItemType = "ScheduleItemType";
			public const string ScheduleType = "ScheduleType";
			public const string ScheduleFrequency = "ScheduleFrequency";
			public const string DailyScheduleType = "DailyScheduleType";
			public const string DailyTimeOfDay = "DailyTimeOfDay";
			public const string DailyFrequency = "DailyFrequency";
			public const string DailyFrequencyType = "DailyFrequencyType";
			public const string UseStartEndTime = "UseStartEndTime";
			public const string DailyStartTime = "DailyStartTime";
			public const string DailyEndTime = "DailyEndTime";
			public const string DayOfWeekMask = "DayOfWeekMask";
		}

		public class SCMLinks
		{
			public const string LinkId = "LinkId";
			public const string ItemId = "ItemId";
			public const string ItemType = "ItemType";
			public const string SCMPath = "SCMPath";
			public const string FileVersion = "FileVersion";
			public const string CreatedBy = "CreatedBy";
			public const string CreatedDateTime = "CreatedDateTime";
		}

		public class SCMSettings
		{
			public const string SCMSettingsId = "SCMSettingsId";
			public const string ProjectId = "ProjectId";
			public const string UserId = "UserId";
			public const string SCMAssembly = "SCMAssembly";
			public const string SettingsXML = "SettingsXML";
		}

		public class SecurityCategories
		{
			public const string SecurityCategoryId = "SecurityCategoryId";
			public const string CategoryName = "CategoryName";
			public const string DisplayOrder = "DisplayOrder";
		}

		public class SecurityFeatures
		{
			public const string SecurityFeatureId = "SecurityFeatureId";
			public const string FeatureName = "FeatureName";
			public const string AffectedByProject = "AffectedByProject";
			public const string SecurityCategoryId = "SecurityCategoryId";
			public const string DisplayOrder = "DisplayOrder";
		}

		public class SecurityRoleFeatures
		{
			public const string SecurityRoleId = "SecurityRoleId";
			public const string SecurityFeatureId = "SecurityFeatureId";
		}

		public class SecurityRoleFields
		{
			public const string SecurityRoleId = "SecurityRoleId";
			public const string FieldId = "FieldId";
		}

		public class SecurityRoleProjects
		{
			public const string SecurityRoleId = "SecurityRoleId";
			public const string ProjectId = "ProjectId";
		}

		public class SecurityRoleReports
		{
			public const string SecurityRoleId = "SecurityRoleId";
			public const string ReportId = "ReportId";
		}

		public class SecurityRoles
		{
			public const string SecurityRoleId = "SecurityRoleId";
			public const string RoleName = "RoleName";
			public const string IsAdmin = "IsAdmin";
			public const string UseDefectFields = "UseDefectFields";
			public const string UseFeatureFields = "UseFeatureFields";
			public const string UseTaskFields = "UseTaskFields";
			public const string UseIncidentFields = "UseIncidentFields";
		}

		public class SeverityTypes
		{
			public const string SeverityTypeId = "SeverityTypeId";
			public const string Name = "Name";
			public const string DisplayOrder = "DisplayOrder";
			public const string DefaultColor = "DefaultColor";
		}

		public class StatusTypes
		{
			public const string StatusTypeId = "StatusTypeId";
			public const string Name = "Name";
			public const string DisplayOrder = "DisplayOrder";
			public const string DefaultColor = "DefaultColor";
		}

		public class TaskCustomFields
		{
			public const string TaskId = "TaskId";
			public const string Custom_149 = "Custom_149";
		}

		public class Tasks
		{
			public const string TaskId = "TaskId";
			public const string TaskNumber = "TaskNumber";
			public const string Name = "Name";
			public const string Description = "Description";
			public const string Notes = "Notes";
			public const string CategoryTypeId = "CategoryTypeId";
			public const string ProjectId = "ProjectId";
			public const string StartDate = "StartDate";
			public const string DueDate = "DueDate";
			public const string CompletionDate = "CompletionDate";
			public const string IsCompleted = "IsCompleted";
			public const string IsPublic = "IsPublic";
			public const string AssignedToId = "AssignedToId";
			public const string ReportedById = "ReportedById";
			public const string CreatedById = "CreatedById";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string LastUpdatedById = "LastUpdatedById";
			public const string LastUpdatedDateTime = "LastUpdatedDateTime";
			public const string LastUpdated = "LastUpdated";
			public const string Archived = "Archived";
			public const string EstimatedDuration = "EstimatedDuration";
			public const string DurationUnitTypeId = "DurationUnitTypeId";
			public const string ActualDuration = "ActualDuration";
			public const string ActualUnitTypeId = "ActualUnitTypeId";
			public const string WorkflowStepId = "WorkflowStepId";
			public const string PriorityTypeId = "PriorityTypeId";
			public const string RemainingDuration = "RemainingDuration";
			public const string RemainingUnitTypeId = "RemainingUnitTypeId";
			public const string ReleaseId = "ReleaseId";
			public const string StatusTypeId = "StatusTypeId";
			public const string PubliclyViewable = "PubliclyViewable";
			public const string ReportedByCustomerContactId = "ReportedByCustomerContactId";
			public const string PercentComplete = "PercentComplete";
		}

		public class TempAppData
		{
			public const string AppKey = "AppKey";
			public const string Data = "Data";
			public const string CreatedDateTime = "CreatedDateTime";
		}

		public class TimeUnitTypes
		{
			public const string TimeUnitTypeId = "TimeUnitTypeId";
			public const string Name = "Name";
			public const string Abbreviation = "Abbreviation";
			public const string DisplayOrder = "DisplayOrder";
			public const string ConversionFactor = "ConversionFactor";
		}

		public class UserLogins
		{
			public const string UserLoginId = "UserLoginId";
			public const string UserId = "UserId";
			public const string ClientType = "ClientType";
			public const string LoginDateTime = "LoginDateTime";
			public const string LoginId = "LoginId";
		}

		public class Users
		{
			public const string UserId = "UserId";
			public const string FirstName = "FirstName";
			public const string LastName = "LastName";
			public const string Email = "Email";
			public const string LoginId = "LoginId";
			public const string Password = "Password";
			public const string WindowsId = "WindowsId";
			public const string UseWindowsAuth = "UseWindowsAuth";
			public const string BuiltInAccount = "BuiltInAccount";
			public const string SettingsXml = "SettingsXml";
			public const string IsActive = "IsActive";
			public const string UseWindowsClient = "UseWindowsClient";
			public const string UseWebClient = "UseWebClient";
			public const string UseVSClient = "UseVSClient";
			public const string UseMixedMode = "UseMixedMode";
			public const string EnterpriseConnectionType = "EnterpriseConnectionType";
			public const string UseIPhoneClient = "UseIPhoneClient";
			public const string LastLoginDateTime = "LastLoginDateTime";
			public const string ReadMessages = "ReadMessages";
			public const string IPhoneSettings = "IPhoneSettings";
			public const string HasReadUpgradeMessage = "HasReadUpgradeMessage";
		}

		public class UserSecurityRoles
		{
			public const string UserId = "UserId";
			public const string SecurityRoleId = "SecurityRoleId";
		}

		public class Views
		{
			public const string ViewId = "ViewId";
			public const string UserId = "UserId";
			public const string ItemType = "ItemType";
			public const string Private = "Private";
			public const string Name = "Name";
			public const string ViewXml = "ViewXml";
		}

		public class Votes
		{
			public const string VoteId = "VoteId";
			public const string ItemId = "ItemId";
			public const string ItemType = "ItemType";
			public const string UserId = "UserId";
			public const string UserType = "UserType";
			public const string VoteNumber = "VoteNumber";
			public const string VoteDate = "VoteDate";
		}

		public class VotesView
		{
			public const string ItemId = "ItemId";
			public const string ItemType = "ItemType";
			public const string VoteCount = "VoteCount";
			public const string VoteAverage = "VoteAverage";
		}

		public class WikiPageHistory
		{
			public const string WikiPageHistoryId = "WikiPageHistoryId";
			public const string WikiPageId = "WikiPageId";
			public const string ProjectId = "ProjectId";
			public const string AuditType = "AuditType";
			public const string ChangeDateTime = "ChangeDateTime";
			public const string ChangedByUserId = "ChangedByUserId";
			public const string ChangedByType = "ChangedByType";
			public const string Title = "Title";
			public const string Body = "Body";
			public const string CommentId = "CommentId";
		}

		public class WikiPages
		{
			public const string WikiPageId = "WikiPageId";
			public const string ProjectId = "ProjectId";
			public const string Title = "Title";
			public const string Body = "Body";
			public const string IsDefaultPage = "IsDefaultPage";
			public const string CreatedById = "CreatedById";
			public const string CreatedDateTime = "CreatedDateTime";
			public const string CreatedByType = "CreatedByType";
			public const string LastUpdatedDateTime = "LastUpdatedDateTime";
			public const string LastUpdatedById = "LastUpdatedById";
			public const string LastUpdatedByType = "LastUpdatedByType";
			public const string PubliclyViewable = "PubliclyViewable";
			public const string PubliclyEditable = "PubliclyEditable";
			public const string LastUpdated = "LastUpdated";
		}

		public class Workflows
		{
			public const string WorkflowId = "WorkflowId";
			public const string WorkflowName = "WorkflowName";
			public const string WorkflowDescription = "WorkflowDescription";
			public const string ItemType = "ItemType";
			public const string IsActive = "IsActive";
		}

		public class WorkflowStepRelations
		{
			public const string WorkflowStepRelationId = "WorkflowStepRelationId";
			public const string WorkflowId = "WorkflowId";
			public const string WorkflowStepFromId = "WorkflowStepFromId";
			public const string WorkflowStepToId = "WorkflowStepToId";
		}

		public class WorkflowStepRelationSecurity
		{
			public const string WorkflowStepRelationSecurityId = "WorkflowStepRelationSecurityId";
			public const string WorkflowStepRelationId = "WorkflowStepRelationId";
			public const string SecurityRoleId = "SecurityRoleId";
		}

		public class WorkflowSteps
		{
			public const string WorkflowStepId = "WorkflowStepId";
			public const string WorkflowId = "WorkflowId";
			public const string StepOrder = "StepOrder";
			public const string StepName = "StepName";
			public const string EditFieldTemplateId = "EditFieldTemplateId";
			public const string RequireEdit = "RequireEdit";
			public const string ChangesFieldTemplateXml = "ChangesFieldTemplateXml";
			public const string RequireCompletedTasks = "RequireCompletedTasks";
			public const string ArchiveItem = "ArchiveItem";
			public const string UnarchiveItem = "UnarchiveItem";
			public const string SuppressNotifications = "SuppressNotifications";
			public const string ProcessPath = "ProcessPath";
			public const string ProcessArguments = "ProcessArguments";
			public const string UpdateTimeEstimate = "UpdateTimeEstimate";
			public const string PromptWorkLogEntry = "PromptWorkLogEntry";
			public const string RequireWorkLogEntry = "RequireWorkLogEntry";
			public const string NewEmailWorkflowStepId = "NewEmailWorkflowStepId";
			public const string ScmCommitWorkflowStepId = "ScmCommitWorkflowStepId";
			public const string DefaultColor = "DefaultColor";
		}

		public class WorkLog
		{
			public const string WorkLogId = "WorkLogId";
			public const string WorkLogDateTime = "WorkLogDateTime";
			public const string ItemId = "ItemId";
			public const string ItemTypeId = "ItemTypeId";
			public const string UserId = "UserId";
			public const string WorkDone = "WorkDone";
			public const string WorkUnitTypeId = "WorkUnitTypeId";
			public const string Description = "Description";
			public const string WorkLogTypeId = "WorkLogTypeId";
		}

		public class WorkLogCustomFields
		{
			public const string WorkLogId = "WorkLogId";
		}

		public class WorkLogTypes
		{
			public const string WorkLogTypeId = "WorkLogTypeId";
			public const string Name = "Name";
			public const string DisplayOrder = "DisplayOrder";
		}

	}
}
